### ISSUE TITLE
Best practices for multi-host system configuration

### ISSUE THREAD

**Issue by soupglasses** [tweag/nix-hour#17]
This is partly inspired by the latest episode, where [nixus was discussed](https://www.youtube.com/live/Gj5LrUmDzHM?feature=share&t=981).

While NixOS is awesome for configuring one computer. I am quite stumped on how i could leverage Nix to connect several machines together. Currently i am simply using DNS lookups trough a VPN or local-connection and just using my own knowledge where the services would connect between the hosts. Preferably we could stay around using `nixos-rebuild --target` and not super large tools like `nixops`.

**Comment by infinisil** [comment]
I don't think this is entirely fit for a Nix hour, because Nix won't be involved for this other than configuring some runtime services. For example, here's some options that I know of to do this:
- Discovery (figuring out which machine to connect to)
  - Hardcoded IPs in Nix
  - DNS records
  - Consul
- Connectivity (how to transmit data between the machines)
  - Public IP
  - Zerotier
  - Some other VPN

I hope this helps, let me know!
