### ISSUE TITLE
How to cross-build an image for the RPi 

### ISSUE THREAD

**Issue by StefanSchroeder** [tweag/nix-hour#60]
There are several manuals out there, describing how to get started on a RPi, but then need to perform some computation/configuration on the target, which is kind of not nice on a comparatively slow/weak device like a RPi.

The goal of this mission is this: Create a dd-able disk image for a Raspberry Pi 3 or later that is ready-to-run.

It could either be built from scratch or by modifying one of the pre-built images from:
https://hydra.nixos.org/job/nixos/release-23.11/nixos.sd_image.aarch64-linux

🙏

**Comment by infinisil** [comment]
Sounds like https://nix.dev/tutorials/nixos/installing-nixos-on-a-raspberry-pi might help here? Let me know! Otherwise I don't think I could really make a Nix Hour about this because I don't have a Raspberry Pi :sweat_smile:

**Comment by StefanSchroeder** [comment]
This manual is doing exactly what I had been diagnosing: You need to configure the system on the target device, e.g. you need to login to the device to configure Wifi. This is exactly the configuration that I'd prefer to do upfront, so that I can also use it for Wifi-only Pi's that are difficult (or impossible) to plug in via Ethernet or HDMI.

**Comment by infinisil** [comment]
Sorry I think this is a bit out of scope, I don't really have the time nor expertise to hack on a Pi right now. For that specific problem though, I'd guess it should be `networking.wireless`, see https://nixos.org/manual/nixos/stable/#sec-wireless. And if this works, it would be great if you could extend the tutorial on nix.dev with that information for future readers. Otherwise I'd suggest asking on Discourse :)

**Comment by StefanSchroeder** [comment]
👍🎄
