### ISSUE TITLE
Module system expedition

### ISSUE THREAD

**Issue by idrisr** [tweag/nix-hour#72]
When using flakes, how can one inspect the values for a particular module option?  For example, when using home-manager or nixvim as a nixos-module, how can I check the values produced for

```
networking.firewall.allowedTCPPorts # nixos module option
programs.zsh.autosuggestion.highlight # home-manager module option
plugins.lsp.servers.hls.enable # nixvim module option
```

How do module options compose when using one module system (like home-manager) within another module system (like nixos).  Does the attribute set declared by home-manager nest entirely within the attribute set of the nixos-declared attributes?

**Comment by infinisil** [comment]
Good question! Since I know a lot about the module system, we decided to cover this topic in tomorrows Nix Hour at 17:00 CET! We'll make it a more general **expedition into the module system**. If anybody has any extra questions about this topic, either:

- Ask them in this issue in advance with a comment
- Join the [livestream](https://youtube.com/live/IBzE0pPOm34) and use the chat to ask questions live
