### ISSUE TITLE
The bootstrap process of `stdenv`

### ISSUE THREAD

**Issue by andreasfelix** [tweag/nix-hour#8]
Hi, thanks for the weekly lectures! I think it would be interesting to see how `stdenv` is bootstraped in `nixpkgs`? How can `stdenv.mkDerivation` be used in the `coreutils` derivation if `coreutils` is a part of `stdenv`? 

For educational purposes, I think it would be also interesting to implement a slimmed-down version of `stdenv` (maybe only `gcc` + `coreutils`) from scratch (without `nixpkgs` as input). I imagine something in the spirit of [micrograd](https://github.com/karpathy/micrograd). This `micro-nixpkgs` would then only contain `micro-stdenv/mkDerivation/mkShell` plus some 1 or 2 packages. As I don't understand the steps necessary to achieve such a `micro-nixpkgs`, I don't know how feasible this would be for a 1 hour lecture. Maybe such a project could be divided into multiple smaller tasks and split along multiple lectures? Just and idea!

**Comment by t184256** [comment]
Shameless plug: If you're interested in how can one bootstrap a working stdenv, but are intimidated with nixpkgs being too big, I have two projects you might be interested in:

1. https://github.com/ZilchOS/bootstrap-from-tcc takes TinyCC compiler and builds a clang toolchain from it. Then it builds Nix and repeats the process under Nix
2. https://github.com/ZilchOS/ZilchOS proceeds to  define a stdenv using this toolchain and build a bootable OS image with Nix.

**Comment by infinisil** [comment]
I'm not an expert on this, but since so many people upvoted this we talked about it [in the last Nix Hour](https://www.youtube.com/watch?v=pTY27vxIXiY&t=1539s). I don't think I can talk more about this, but @t184256's above-linked alternate bootstrapping projects also looks very interesting!

If there's more questions you have about this topic, feel free to open a new issue :D
